services:
  app:
    build: .
    container_name: self-destruct-note
    restart: always
    ports:
      - "80:8080"
    environment:

      # IP сервера Yandex Cloud
      APP_BASE_URL: "http://localhost:8080"

      CUSTOM_SECURITY_ENCRYPTION_KEY: "AUJDFHETSOMLKDJH"